algoritmo "Sequência de Fibonacci"

var
  contador, final, algarismo1, algarismo2, algarismo3: Inteiro
inicio
Escreval("Até qual número da sequência Fibonacci deseja ver?")
Escreva("desejo ver até: ")
Leia(final)
algarismo1 <- 0
Escreval(algarismo1)
algarismo2 <- 1
Escreval(algarismo2)
Para contador <- 3 ate final faca
     algarismo3 <- algarismo1 + algarismo2
     Escreval(algarismo3)
     algarismo1 <- algarismo2
     algarismo2 <- algarismo3
FimPara
fimalgoritmo
